"""init

Revision ID: 0cee6043afcd
Revises: 
Create Date: 2026-05-17 06:20:54.572726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cee6043afcd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('report_text', sa.Text(), nullable=False),
    sa.Column('conclusion', sa.Enum('BLOCKING', 'EVERYTHING_IS_FINE', name='conclusionenum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_reports_comment_id'), 'comment_reports', ['comment_id'], unique=False)
    op.create_index(op.f('ix_comment_reports_user_id'), 'comment_reports', ['user_id'], unique=False)
    op.create_table('film_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('film_id', sa.UUID(), nullable=False),
    sa.Column('new_category', sa.Text(), nullable=False),
    sa.Column('review', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_film_reviews_film_id'), 'film_reviews', ['film_id'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('report_text', sa.Text(), nullable=False),
    sa.Column('conclusion', sa.Enum('BLOCKING', 'EVERYTHING_IS_FINE', name='conclusionenum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.create_table('news_film_reviews',
    sa.Column('news_id', sa.UUID(), nullable=False),
    sa.Column('film_review_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('news_id', 'film_review_id')
    )
    op.create_table('report_comments',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id', 'comment_id')
    )
    op.create_table('report_related_reports',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('related_report_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id', 'related_report_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_related_reports')
    op.drop_table('report_comments')
    op.drop_table('news_film_reviews')
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_table('news')
    op.drop_index(op.f('ix_film_reviews_film_id'), table_name='film_reviews')
    op.drop_table('film_reviews')
    op.drop_index(op.f('ix_comment_reports_user_id'), table_name='comment_reports')
    op.drop_index(op.f('ix_comment_reports_comment_id'), table_name='comment_reports')
    op.drop_table('comment_reports')
    # ### end Alembic commands ###
