import enum
from uuid import uuid4

from sqlalchemy import UUID, Column, DateTime, Text, func

from src.domain.models.base import Base


class ConclusionEnum(str, enum.Enum):
    BLOCKING = "blocking"
    EVERYTHING_IS_FINE = "everything_is_fine"


class CommentReport(Base):
    __tablename__ = "comment_reports"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    comment_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    user_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    date = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    # Large text generated by LLM after Arseniy's service processes the comment
    report_text = Column(Text, nullable=False)
    conclusion = Column(Text, nullable=True)

    def __init__(
        self,
        comment_id,
        user_id,
        report_text: str,
        conclusion: ConclusionEnum | str | None = None,
    ) -> None:
        self.comment_id = comment_id
        self.user_id = user_id
        self.report_text = report_text
        if isinstance(conclusion, ConclusionEnum):
            self.conclusion = conclusion.value
        else:
            self.conclusion = conclusion
